# dbt_project.yml

name: 'irembo_analytics_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which folder to look for models in.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL and artifacts
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configure profiles to be loaded from the project directory
profile: 'irembo_analytics_dbt'

models:
  irembo_analytics_dbt:
    marts:
      fact_voice_ai_sessions:
        +post-hook:
          - "COPY {{ this }} TO '../outputs/fact_voice_ai_sessions.csv' (HEADER, DELIMITER ',')"